### ISSUE TITLE
Fan Speed resets after Wakeup from suspend

### ISSUE THREAD

**Issue by Schabolon** [dmitry-s93/MControlCenter#151]
Hi,
first off I wanted to say that this project is really amazing and finally allowed me to control the fan speed.
But when I wake my Laptop up (after suspend) the fan speed goes back to the "default" values.
Is this intended? Or is there a workaround?
I am using a MSI Katana GF76-11UC.

**Comment by 7tg** [comment]
Same here

**Comment by ismailgamedev** [comment]
Same problem

**Comment by Jiogo18** [comment]
Same problem,
fanModeAddress in my case is `0xF4` (it can also be at `0xD4`)
run `sudo hexdump -C /sys/kernel/debug/ec/ec0/io` and look at the value at `0xF4`:
- Before sleep: 0x8d
- After sleep: 0x0d
- Click 2 times on "Enable advanced fan control" ⇒ goes back to 0x8d
- Or restart MControlCenter ⇒ goes back to 0x8d

Possible solutions:
- detect sleep with Qt (I don't know if it is possible)
- create a script/task that executes on wake-up, in order to:
  - execute MControlCenter with a specific command (requires handling commands)
  - kill and restart MControlCenter (bad)
  -  set the value with another tool
- create a timer to force the value all the time (bad)
